Thu Sep  7 19:12:31 IST 2017 crash report /var/crash/_usr_bin_node.1000.crash detected
Traceback (most recent call last):
  File "/usr/share/apport/apport-gtk", line 597, in <module>
    app.run_argv()
  File "/usr/lib/python3/dist-packages/apport/ui.py", line 687, in run_argv
    return self.run_crashes()
  File "/usr/lib/python3/dist-packages/apport/ui.py", line 238, in run_crashes
    logind_session[1] > self.report.get_timestamp():
TypeError: unorderable types: float() > NoneType()
